version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
       - postgres:/data/postgres
       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  app:
    image: lucasrodrigues062/soat42
    container_name: soat42
    ports:
      - "3000:3000"
    restart: unless-stopped 
    networks:
      - postgres
    depends_on:
      - postgres   

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
